### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by arezaie14** [Requarks/connect-loki#8]
Some times Below Error happening and I couldn't know what is the problem. can you please check.

TypeError: Cannot read property 'find' of undefined
at LokiStore.get (C:\node_modules\connect-loki\lib\connect-loki.js:98:29)
at session (C:\node_modules\express-session\index.js:481:11)
at Layer.handle [as handle_request] (C:\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\node_modules\express\lib\router\index.js:317:13)
at C:\node_modules\express\lib\router\index.js:284:7
at Function.process_params (C:\node_modules\express\lib\router\index.js:335:12)
at next (C:\node_modules\express\lib\router\index.js:275:10)
at expressInit (C:\node_modules\express\lib\middleware\init.js:40:5)
at Layer.handle [as handle_request] (C:\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\node_modules\express\lib\router\index.js:317:13)
at C:\node_modules\express\lib\router\index.js:284:7
at Function.process_params (C:\node_modules\express\lib\router\index.js:335:12)
at next (C:\node_modules\express\lib\router\index.js:275:10)
at query (C:\node_modules\express\lib\middleware\query.js:45:5)
at Layer.handle [as handle_request] (C:\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\node_modules\express\lib\router\index.js:317:13)

**Comment by oucifkarim01** [comment]
Hi , I had this problem too before and I have fixed it on my localhost version , I will try to upload the fix.

**Comment by IETF-Zulip** [comment]
> Đôi khi lỗi bên dưới xảy ra và tôi không biết vấn đề là gì. Bạn vui lòng kiểm tra nhé.
> 
> TypeError: Không thể đọc thuộc tính 'find' của undefined tại LokiStore.get (C:\node_modules\connect-loki\lib\connect-loki.js:98:29) tại phiên (C:\node_modules\express-session\index.js:481:11) tại Layer.handle [dưới dạng handle_request] (C:\node_modules\express\lib\router\layer.js:95:5) tại trim_prefix (C:\node_modules\express\lib\router\index.js:317:13) tại C:\node_modules\express\lib\router\index.js:284:7 tại Function.process_params (C:\node_modules\express\lib\router\index.js:335:12) tại next (C:\node_modules\express\lib\router\index.js:275:10) tại expressInit (C:\node_modules\express\lib\middleware\init.js:40:5) tại Layer.handle [dưới dạng handle_request] (C:\node_modules\express\lib\router\layer.js:95:5) tại trim_prefix (C:\node_modules\express\lib\router\index.js:317:13) tại C:\node_modules\express\lib\router\index.js:284:7 tại Function.process_params (C:\node_modules\express\lib\router\index.js:335:12) tại next (C:\node_modules\express\lib\router\index.js:275:10) tại query (C:\node_modules\express\lib\middleware\query.js:45:5) tại Layer.handle [dưới dạng handle_request] (C:\node_modules\express\lib\router\layer.js:95:5) tại tiền tố cắt (C:\node_modules\express\lib\router\index.js:317:13)
https://github.com/requarks/connect-loki/issues/8
https://github.com/requarks/connect-loki/issues/8#issue-641312742
